- name: ArgoCD
  hosts: all
  #vars:
  collections:
  - kubernetes.core
  tasks:

  - name: Create argocd k8s namespace
    kubernetes.core.k8s:
      name: argocd
      api_version: v1
      kind: Namespace
      state: present

  - name: Add stable chart repo
    kubernetes.core.helm_repository:
      name: stable
      repo_url: "https://argoproj.github.io/argo-helm"

  - name: Deploy latest version 
    kubernetes.core.helm:
     name: argocd
     chart_ref: stable/argo-cd
     release_namespace: argocd
     values:
      replicas: 2
 
  - name: Get a list of all pods from argocd
    kubernetes.core.k8s_info:
      kind: Pod
      namespace: argocd
    register: pod_list


  - name: Pod List
    ansible.builtin.debug:
      msg:  {{ pod_list }}
