- name: ArgoCD
  hosts: all
  #vars:
  collections:
  - kubernetes.core
  tasks:

  - name: Create argocd k8s namespace
    kubernetes.core.k8s:
      name: argocd
      api_version: v1
      kind: Namespace
      state: present

  - name: Fix directory
    ansible.builtin.set_fact:
      download_path: "{{ playbook_dir }}/download"

  - name: Creates directory
    ansible.builtin.file:
      path: "{{ download_path }}"
      state: directory

  - name: Download something to Ansible Controller
    delegate_to: localhost
    get_url:
     url: "https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.6/manifests/install.yaml"
     dest: "{{ download_path }}"
     #owner: "{{ ansible_user }}"
  
  - name: Argocd deploy
    kubernetes.core.k8s:
      state: present
      src: "{{ download_path }}/install.yaml" 
      kind: Deployment
      namespace: argocd

  - name: Get a list of all pods from argocd
    kubernetes.core.k8s_info:
      kind: Pod
      namespace: argocd
    register: pod_list

  - name: Print pod list
    ansible.builtin.debug:
      msg: "{{ pod_list }}"
