apiVersion: v1
kind: ServiceAccount
metadata:
  name: awx-deployer
  namespace: awx
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-deployer-token
  namespace: awx
  annotations:
    kubernetes.io/service-account.name: awx-deployer
type: kubernetes.io/service-account-token

