- name: CXonn
  hosts: all, !deblaptop1
  #become: true
  gather_facts: false
  vars:
    ansible_python_interpreter: auto_silent
  tasks:
    #- name: A
    #  become: true
    #  ansible.builtin.setup:
    #    gather_subset:
    #      - '!all'
    #      - '!min'
    #      - '!env'
    #- name: B
    #  ansible.builtin.debug:
    #    msg: "{{ ansible_env }}"

    - name: Install Helm env plugin
      ansible.builtin.ping:
      register: ping_status
      ignore_errors: yes

    - name: Setting facts so that they will be persisted in the fact cache
      ansible.builtin.set_fact:
        connectivity:  "{{ 'OK' if ping_status is defined and ping_status.ping is defined and ping_status.ping=='pong' else 'NOK' }} "
        cacheable: yes
   
    - name: gather all facts for {{ inventory_hostname }}
      debug:
        var: ansible_facts
