apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret
  namespace: gitlab
  annotations: 
    kubernetes.io/service-account.name: gitlab-service-account
type: kubernetes.io/service-account-token
