- name: Gitlab Deployment
  hosts: alla
  tasks:

  - name: Add stable Gitlab Chart Repository
    kubernetes.core.helm_repository:
      name: gitlab
      repo_url: "https://charts.gitlab.io/"

  - name: Deploy stable Gitlab Chart  namespace with values
    kubernetes.core.helm:
      name: gitlab
      release_name: gitlab
      chart_ref: gitlab/gitlab
      namespace: gitlab
      values:
        replicas: 3
    