- name: Gitlab Deployment
  hosts: all
  tasks:

  - name: Add stable Gitlab Chart Repository
    kubernetes.core.helm_repository:
      name: gitlab
      repo_url: "https://charts.gitlab.io/"

  - name: Deploy stable Gitlab Chart  namespace with values
    kubernetes.core.helm:
      name: gitlab
      release_name: gitlab
      chart_ref: gitlab/gitlab
      namespace: gitlab
      values:
        replicas: 3
        timeput: 600s
      set_values:
        - value: global.hosts.domain=davcar.com/gitlab
          value_type: string
        - value: global.hosts.externalIP=10.10.10.10
          value_type: string
        - value: certmanager-issuer.email=david.carrio@gmail.com
          value_type: string  
        - value: global.edition=ce
          value_type: string  
        
    



