- name: kube test
  hosts: all
  #vars:
  #  ansible_connection: kubernetes.core.kubectl
  tasks:

  #- name: Add stable chart repo
  #  kubernetes.core.helm_repository:
  #    name: stable
  #    repo_url: "https://kubernetes.github.io/ingress-nginx"

  - name: Install Helm env plugin
    kubernetes.core.helm_plugin:
      plugin_path: https://github.com/adamreese/helm-env
      state: present

  - name: Gather Helm env plugin info
    kubernetes.core.helm_plugin_info:
      plugin_name: env
