- name: kube test
  hosts: localhost
  connection: local
  tasks:

    - name: Prova conexió
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: test-connection
        validate_certs: no

